### ISSUE TITLE
Reconsiderar tiempos

### ISSUE THREAD

**Issue by Peque** [open-robosports/normativa-laberinto#2]
Propongo un tiempo de 8 minutos por participante, a tiempo corrido. Ahora mismo son 5 + 3 + 3 + 3 con pausas entre medias, haciéndose la competición menos dinámica.

En ese tiempo el participante puede realizar tantos intentos como quiera para llegar a la meta. Todos cuentan de cara a la clasificación final.

No habría diferenciación entre fase de exploración y de carrera.

**Comment by JavierIH** [comment]
Me parece bien, pueden hacerse excesivamente largas las competiciones con 14 minutos por robot.

También uno de los objetivos de estas normativas es también intentar compatibilizarlas con las competiciones que ya existen. Estoy viendo que en los [RoboGames](http://robogames.net/rules/maze.php) dan 10 minutos seguidos, en la [micromouse portuguesa](http://www.micromouse.utad.pt/?page_id=504&lang=en) también 10 minutos y en la [micromouse japonesa](https://www.ntf.or.jp/mouse/micromouse2017/kitei_classic_since2014-EN.html) dicen que por defecto 10 (y max 5 intentos), pero podrían ser 7 o 5 dependiendo del evento.

**Comment by Peque** [comment]
Genial, 10 entonces. :+1:

Dejo el asunto abierto hasta que se incluya el cambio en la normativa.
