### ISSUE TITLE
¿Cómo formar parte de la organización `open-robosports`?

### ISSUE THREAD

**Issue by Peque** [open-robosports/normativa-laberinto#3]
Me gustaría saber si es posible pasar a formar parte de la organización para participar, al menos con voz (si no voto), en la toma de decisiones con respecto a la normativa de laberinto.

Creo que todo cambio en la normativa debería hacerse mediante "pull requests" sometiéndose a discusión por parte de aquellos interesados (entiendo que serían siempre participantes de estas competiciones).

**Comment by JavierIH** [comment]
Hola! Sobre realizar cambios en la normativa con pull requests, **absolutamente de acuerdo**. Lo que no tenemos decidido aún es cual será el sistema para tomar decisiones para admitir miembros, aceptar cambios en la normativa... etc Sobre todo porque somos muy pocos.

Creo que dado el estado actual del proyecto, con contribuir ya es suficiente para entrar a ser parte de la organización, así que si estás de acuerdo te mando invitación :smiley:

**Comment by Peque** [comment]
Genial, recibida y aceptada! :blush:
